<?php

namespace models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;
use models\UserOptions;

class Categories extends ActiveRecord
{
    public static function tableName()
    {
        return '{{categories}}';
    }

    public function getTitle(){
        if($this->name) {
            return $this->name;
        }return '';
    }
    public function beforeSave($insert)
    {
        /*
        if($c = self::find()->where(['sub_id' => $this->sub_id])->orderBy('sort desc')->one()){
            if($this->sort == null) {
                $this->sort = $c->sort + 1;
            }
        }*/
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}