<?php

namespace models;

use Yii;
use yii\base\NotSupportedException;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;
use yii\web\IdentityInterface;


class FbsToken extends ActiveRecord
{
    public function __construct($config = [])
    {
        parent::__construct($config);
    }

    public static function tableName()
    {
        return '{{token}}';
    }
    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}