<?php
/**
 * Created by PhpStorm.
 * User: Stomick
 * Date: 19.07.2018
 * Time: 17:06
 */

namespace models;


use yii\behaviors\TimestampBehavior;
use yii\db\ActiveRecord;

class Orders extends ActiveRecord
{
    public static function tableName()
    {
        return 'orders';
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    public function getTotalPrice(){
        return $this->summ;
    }

    public function getId(){
        return $this->order_id;
    }

    public function beforeSave($insert)
    {
        if($this->GUID == null) {
            $this->GUID = self::generateGuid();
        }
        if($this->status == 'succeeded'){
            $us = MUser::findOne($this->user_id);
            $us->balance += $this->summ;
            $us->update();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    function generateGuid($include_braces = false) {
        if (function_exists('com_create_guid')) {
            if ($include_braces === true) {
                return com_create_guid();
            } else {
                return substr(com_create_guid(), 1, 36);
            }
        } else {
            mt_srand((double) microtime() * 10000);
            $charid = md5(uniqid(rand(), true));

            $guid = substr($charid,  0, 8) . '-' .
                substr($charid,  8, 4) . '-' .
                substr($charid, 12, 4) . '-' .
                substr($charid, 16, 4) . '-' .
                substr($charid, 20, 12);

            if ($include_braces) {
                $guid = '{' . $guid . '}';
            }

            return $guid;
        }
    }

}